### ISSUE TITLE
Does not build with GIMP 2.10

### ISSUE THREAD

**Issue by bzed** [muggenhor/focus-blur#1]
Hi,

are you going to maintain the plugin? If so it would be very appreciated if you could fix it for GIMP 2.10.

Thanks!

**Comment by night-codes** [comment]
Same problem

**Comment by venomgfx** [comment]
Winter is coming! :)

I hope you manage to find some time, this plugin is great!

**Comment by muggenhor** [comment]
As described in #2.

I'm closing issue tracking for this repository. Because my primary purpose of putting this on GitHub was to give this code, written by someone else, a place to be hosted where it's possible to work on at a later date.
